-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Users"
(
    "UserID" serial,
    "Username" character varying[],
    "CreatedAt" date,
    PRIMARY KEY ("UserID"),
    CONSTRAINT "UQ_Username" UNIQUE ("Username")
);

CREATE TABLE IF NOT EXISTS public."Photos"
(
    "PhotoID" serial,
    "ImageURL" character varying[],
    "UserId" integer,
    "PublicationDate" date,
    PRIMARY KEY ("PhotoID")
);

CREATE TABLE IF NOT EXISTS public."Likes"
(
    "UserId" serial,
    "PhotoId" integer,
    "DateOfLike" date,
    CONSTRAINT "PK_Likes" PRIMARY KEY ("UserId")
        INCLUDE("UserId", "PhotoId")
);

CREATE TABLE IF NOT EXISTS public."Follow"
(
    follower_id integer,
    followee_id integer,
    follow_date date,
    PRIMARY KEY (follower_id, followee_id)
);

ALTER TABLE IF EXISTS public."Photos"
    ADD CONSTRAINT "FK_Likes_Photos" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Likes"
    ADD CONSTRAINT "FK_Likes_Users" FOREIGN KEY ("UserId")
    REFERENCES public."Users" ("UserID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Likes"
    ADD CONSTRAINT "FK_Likes_Photos" FOREIGN KEY ("PhotoId")
    REFERENCES public."Photos" ("PhotoID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Follow"
    ADD FOREIGN KEY (follower_id, followee_id)
    REFERENCES public."Users" ("UserID", "UserID") MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;